[options]
addons_path = /mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons
admin_passwd = $pbkdf2-sha512$600000$mzMGYIwRwvh/D.HcuzdmzA$0ReP2lRa.tZK/I7advS/lJc.QrAmqnFgvmhr8rnCi1.xRUMbU8otLKqKUqCHeGwS3Ix72.eCsFzqgUcT6PiIWw

